#Snakemake configuration file

#Specify paths to data files

#Paths must end with forward slash

#project directory
dir_proj: /project2/gilad/briana/apaQTL/


#ref genome directory
dir_anno: /project2/gilad/briana/genome_anotation_data/
dir_genome: /project2/gilad/briana/genome_anotation_data/star_genome
file_vcf: /project2/gilad/briana/YRI_geno_hg19/allChrom.dose.filt.vcf
file_genomeFA: /project2/gilad/briana/genome_anotation_data/genome/Homo_sapiens.GRCh37.75.dna_sm.all.fa

file_chromorder: /project2/gilad/briana/genome_anotation_data/chromOrder.num.txt
#chrom lengths
chrom_lenght: /project2/gilad/briana/genome_anotation_data/chrom.length.txt


#files for picard:
ref_flat: /project2/gilad/briana/genome_anotation_data/gencode.v19.annotation2.nochr.refFlat
ribosome_intervals: /project2/gilad/briana/genome_anotation_data/hg19.rRNA.intervals


#directory with aditional scripts:
scripts: /project2/gilad/briana/apaQTL/code/

# Make sure to also update path for log files in cluster.json
dir_log: log/

# Specify Ensembl release for genome sequence and annotation
# http://feb2014.archive.ensembl.org/index.html
ensembl_archive: feb2014.archive.ensembl.org
ensembl_rel: 75
ensembl_genome: GRCh37.75

#Specify chromosomes

# For quantifying gene expression
chr_genes: ["1", "2", "3", "4", "5", "6", "7", "8", "9","10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22","X", "Y", "MT"]
